name: skycast
description: "SkyCast, to check your prefer localization weather"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  get_it: ^7.6.6
  http: ^1.1.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  intl: ^0.18.1
  localization: ^2.1.1
  flutter_localization: ^0.2.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  flutter_hooks: ^0.20.4
  google_fonts: ^6.1.0

  animated_text_kit: ^4.2.2

  dynamic_color: ^1.6.9
  responsive_framework: ^1.1.1
  lottie: ^2.7.0
  flutter_dotenv: ^5.1.0

  hooks_riverpod: ^2.4.9
  cached_network_image: ^3.3.1
  riverpod_annotation: ^2.3.3
  side_navigation: ^1.0.4

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  freezed: ^2.4.6
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  husky: ^0.1.6
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  mockito: 5.4.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - .env
    # this is for make the test widget, found the Poppins fonts
    - assets/fonts/poppins/
    # this is for make the test widget, found the Lato fonts
    - assets/fonts/lato/
    - assets/lottie/loading/
    - assets/lottie/success/
    - assets/lottie/error/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Light.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Light.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
          style: italic

