#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

flutter test
dart format . -l 120 --set-exit-if-changed
dart analyze --fatal-infos --fatal-warnings .
