name: Flutter Web
on:
  push:
    branches:
      - main
      - SETUP-01-setup-firebase-final
jobs:
  build:
    name: 🚀 Build Web on develop
    env:
      my_secret: ${{secrets.PAT}}
      weather_api_key: ${{secrets.WEATHER_API_KEY}}
      google_maps_api_key: ${{secrets.GOOGLE_MAPS_API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Create env file'
        run: |
          touch env &&
          echo ENV=production >> env &&
          echo API_KEY=${{env.weather_api_key}} >> env &&
          echo BASE_URL_WEATHER=api.weatherapi.com >> env &&
          echo PATH_FORECAST=/forecast.json >> env &&
          echo PREFIX_URL_WEATHER=/v1 >> env &&
          echo PATH_FORECAST=/forecast.json >> env &&
          echo PATH_CONDITION_TRANSLATIONS=/docs/conditions.json >> env &&
          echo GOOGLE_MAPS_API_KEY=${{env.google_maps_api_key}} >> env &&
          echo PATH_TO_GET_SUGGESTIONS_FOR_DIRECTIONS=/maps/api/place/autocomplete/json >> env &&
          echo BASE_URL_TO_GET_MAP_DIRECTIONS=maps.googleapis.com >> env &&
          cat env

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.4'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --base-href=/skycast/
      - run: |
          cd build/web
          git init
          git config --global user.email carlos.hernandez3@catolica.edu.sv
          git config --global user.name g14wx
          git status
          git remote add origin https://${{env.my_secret}}@github.com/g14wx/skycast.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update web"
          git push origin gh-pages -f